# Generated by Django 4.2.5 on 2023-09-07 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_customer_preference_orders_products_delete_articles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_preference',
            name='preference_id',
            field=models.CharField(max_length=5),
        ),
    ]
